"""Add remaining Epic 1 entities: sections, courses, rooms, time_slots, constraints

Revision ID: 630f4caa546f
Revises: 1c16dc0d0f3a
Create Date: 2026-01-27 21:51:55.320060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '630f4caa546f'
down_revision: Union[str, None] = '1c16dc0d0f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rule_definition', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("constraint_type IN (\n                'NO_FACULTY_CLASH', 'NO_ROOM_CLASH', 'NO_STUDENT_CLASH',\n                'WORKLOAD_LIMIT', 'ROOM_CAPACITY', 'LAB_REQUIREMENT',\n                'PREFERENCE_TIME', 'PREFERENCE_DAY', 'MAX_CONSECUTIVE',\n                'MIN_BREAK', 'MAX_COMMUTE', 'ELECTIVE_NO_CLASH'\n            )", name='check_constraint_type_valid'),
    sa.CheckConstraint('priority >= 0 AND priority <= 1000', name='check_priority_range'),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='check_weight_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_id'), 'constraints', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('has_projector', sa.Boolean(), nullable=True),
    sa.Column('has_lab_equipment', sa.Boolean(), nullable=True),
    sa.Column('has_ac', sa.Boolean(), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("room_type IN ('classroom', 'lab', 'auditorium', 'seminar_hall')", name='check_room_type_valid'),
    sa.CheckConstraint('capacity > 0', name='check_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=True)
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')", name='check_day_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    op.create_table('elective_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elective_groups_id'), 'elective_groups', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('theory_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('elective_group_id', sa.Integer(), nullable=True),
    sa.Column('requires_lab', sa.Boolean(), nullable=True),
    sa.Column('min_room_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('credits > 0', name='check_credits_positive'),
    sa.CheckConstraint('lab_hours >= 0', name='check_lab_hours_nonnegative'),
    sa.CheckConstraint('theory_hours + lab_hours > 0', name='check_hours_positive'),
    sa.CheckConstraint('theory_hours >= 0', name='check_theory_hours_nonnegative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['elective_group_id'], ['elective_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_elective_groups_id'), table_name='elective_groups')
    op.drop_table('elective_groups')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_constraints_id'), table_name='constraints')
    op.drop_table('constraints')
    # ### end Alembic commands ###
