"""Add tutorial_hours to Course model

Revision ID: dae96d87de70
Revises: 630f4caa546f
Create Date: 2026-01-27 22:38:00.338113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae96d87de70'
down_revision: Union[str, None] = '630f4caa546f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('tutorial_hours', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'tutorial_hours')
    # ### end Alembic commands ###
